import { useEffect, useState } from "react";
import { Link2, LoaderCircle, Mail, Paperclip, RefreshCw, Search } from "lucide-react";
import { ApiError, api } from "../../api";
import type { EmailMessage } from "../../domain";

export function EmailsWorkspace({ onOpenSettings }: { onOpenSettings: () => void }) {
  const [emails, setEmails] = useState<EmailMessage[]>([]);
  const [selectedId, setSelectedId] = useState<string>();
  const [detail, setDetail] = useState<EmailMessage>();
  const [search, setSearch] = useState("");
  const [loading, setLoading] = useState(true);
  const [syncing, setSyncing] = useState(false);
  const [error, setError] = useState<string>();

  const load = async (signal?: AbortSignal) => { setLoading(true); try { const next = await api.emails.list(search, signal); setEmails(next); setSelectedId(current => current && next.some(x => x.id === current) ? current : next[0]?.id); setError(undefined); } catch (e) { if ((e as Error).name !== "AbortError") setError("E-maily se nepodařilo načíst."); } finally { setLoading(false); } };
  useEffect(() => { const controller = new AbortController(); const timeout = window.setTimeout(() => void load(controller.signal), 180); return () => { window.clearTimeout(timeout); controller.abort(); }; }, [search]);
  useEffect(() => { if (!selectedId) { setDetail(undefined); return; } const controller = new AbortController(); api.emails.detail(selectedId, controller.signal).then(next => { setDetail(next); setEmails(current => current.map(x => x.id === next.id ? next : x)); }).catch(e => { if ((e as Error).name !== "AbortError") setError("Detail e-mailu se nepodařilo načíst."); }); return () => controller.abort(); }, [selectedId]);

  const sync = async () => { setSyncing(true); setError(undefined); try { await api.emails.sync(); await load(); } catch (e) { if (e instanceof ApiError && (e.status === 400 || e.status === 404)) { setError(e.message); onOpenSettings(); } else setError("Synchronizace e-mailů se nepodařila."); } finally { setSyncing(false); } };

  return <div className="split-view email-workspace"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">KOMUNIKACE</p><h1>E-maily</h1></div><button className="primary email-sync" onClick={sync} disabled={syncing}>{syncing ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />} Synchronizovat</button></header><div className="toolbar"><label className="search"><Search size={16} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Hledat odesílatele nebo předmět…" /></label></div>{error && <div className="error-banner">{error}</div>}<div className="email-list">{loading ? <div className="loader"><LoaderCircle className="spin" /> Načítám e-maily…</div> : emails.map(email => <button key={email.id} className={`email-row ${selectedId === email.id ? "selected" : ""} ${email.isRead ? "" : "unread"}`} onClick={() => setSelectedId(email.id)}><span className="email-row-icon"><Mail size={17} /></span><span className="email-row-copy"><b>{email.fromName || email.fromAddress}</b><strong>{email.subject}</strong><small>{email.businessPartnerName || email.orderNumber || "Bez přiřazení"}</small></span><span className="email-row-meta">{email.hasAttachments && <Paperclip size={13} />}{formatDate(email.occurredAtUtc)}</span></button>)}{!loading && emails.length === 0 && <div className="no-results">Schránka je prázdná. Nastavte účet a spusťte synchronizaci.</div>}</div></section><section className="detail-pane">{detail ? <EmailDetail email={detail} onChange={next => { setDetail(next); setEmails(current => current.map(x => x.id === next.id ? next : x)); }} /> : <div className="detail-placeholder"><Mail size={36} /><p>Vyberte e-mail ze seznamu.</p></div>}</section></div>;
}

function EmailDetail({ email, onChange }: { email: EmailMessage; onChange: (email: EmailMessage) => void }) {
  const [partnerId, setPartnerId] = useState(email.businessPartnerId ?? ""); const [orderId, setOrderId] = useState(email.orderId ?? ""); const [saving, setSaving] = useState(false);
  const [partners, setPartners] = useState<{ id: string; name: string }[]>([]); const [orders, setOrders] = useState<{ id: string; number: string; title: string }[]>([]);
  useEffect(() => { setPartnerId(email.businessPartnerId ?? ""); setOrderId(email.orderId ?? ""); }, [email.id, email.businessPartnerId, email.orderId]);
  useEffect(() => { const controller = new AbortController(); Promise.all([api.orders.list("", "number", true, controller.signal), ...(["Customer", "Lead", "Supplier", "Warehouse", "Carrier", "CustomsDeclarant", "Collaborator"] as const).map(type => api.partners.list(type, "", controller.signal))]).then(([orderResult, ...partnerResults]) => { setOrders(orderResult.items.map(x => ({ id: x.id, number: x.number, title: x.title }))); setPartners(partnerResults.flatMap(x => x.items).map(x => ({ id: x.id, name: x.name })).sort((a, b) => a.name.localeCompare(b.name, "cs"))); }).catch(e => { if ((e as Error).name !== "AbortError") console.error(e); }); return () => controller.abort(); }, []);
  const saveLink = async () => { setSaving(true); try { onChange(await api.emails.link(email.id, partnerId, orderId)); } finally { setSaving(false); } };
  return <><header className="detail-header"><div><p className="eyebrow">{email.direction === "Inbound" ? "PŘÍCHOZÍ E-MAIL" : "ODESLANÝ E-MAIL"}</p><h2>{email.subject}</h2><p>{email.fromName ? `${email.fromName} · ${email.fromAddress}` : email.fromAddress} → {email.toAddress}</p></div></header><div className="email-link-bar"><Link2 size={16} /><label>Partner <select value={partnerId} onChange={e => setPartnerId(e.target.value)}><option value="">Bez přiřazení</option>{partners.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Zakázka <select value={orderId} onChange={e => setOrderId(e.target.value)}><option value="">Bez přiřazení</option>{orders.map(x => <option key={x.id} value={x.id}>{x.number} · {x.title}</option>)}</select></label><button className="secondary" onClick={saveLink} disabled={saving}>Uložit vazbu</button></div><div className="email-detail-content"><div className="email-envelope"><span><b>Od:</b> {email.fromAddress}</span><span><b>Komu:</b> {email.toAddress}</span><span><b>Datum:</b> {new Intl.DateTimeFormat("cs-CZ", { dateStyle: "long", timeStyle: "short" }).format(new Date(email.occurredAtUtc))}</span></div>{email.bodyHtml ? <iframe title="Obsah e-mailu" sandbox="" srcDoc={email.bodyHtml} /> : <pre>{email.bodyText || "E-mail nemá textový obsah."}</pre>}</div></>;
}

function formatDate(value: string) { const date = new Date(value); return date.toLocaleDateString("cs-CZ", { day: "2-digit", month: "2-digit" }); }
