import { useState } from "react";
import { FileText, LoaderCircle, Mail, Paperclip, RefreshCw, Search } from "lucide-react";
import { EmailDetail } from "./EmailDetail";
import { EmailTemplatesModal } from "./EmailTemplatesModal";
import { useEmailsWorkspace } from "./useEmailsWorkspace";

export function EmailsWorkspace({ onOpenSettings }: { onOpenSettings: () => void }) {
  const state = useEmailsWorkspace(onOpenSettings); const [templatesOpen, setTemplatesOpen] = useState(false);
  return <div className="split-view email-workspace"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">KOMUNIKACE</p><h1>E-maily</h1></div><div className="email-actions"><button className="secondary" onClick={() => setTemplatesOpen(true)}><FileText size={15} /> Šablony</button><button className="primary email-sync" onClick={state.sync} disabled={state.syncing}>{state.syncing ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />} Synchronizovat</button></div></header><div className="toolbar"><label className="search"><Search size={16} /><input value={state.search} onChange={event => state.setSearch(event.target.value)} placeholder="Hledat odesílatele nebo předmět…" /></label></div>{state.error && <div className="error-banner">{state.error}</div>}<div className="email-list">{state.loading ? <div className="loader"><LoaderCircle className="spin" /> Načítám e-maily…</div> : state.emails.map(email => <button key={email.id} className={`email-row ${state.selectedId === email.id ? "selected" : ""} ${email.isRead ? "" : "unread"}`} onClick={() => state.setSelectedId(email.id)}><span className="email-row-icon"><Mail size={17} /></span><span className="email-row-copy"><b>{email.direction === "Outbound" ? `Komu: ${email.toAddress}` : email.fromName || email.fromAddress}</b><strong>{email.subject}</strong><small>{email.businessPartnerName || email.orderNumber || "Bez přiřazení"}</small></span><span className="email-row-meta">{email.hasAttachments && <Paperclip size={13} />}{formatDate(email.occurredAtUtc)}</span></button>)}{!state.loading && state.emails.length === 0 && <div className="no-results">Schránka je prázdná. Nastavte účet a spusťte synchronizaci.</div>}</div></section><section className="detail-pane">{state.detail ? <EmailDetail email={state.detail} onChange={state.updateEmail} onSent={state.addEmail} /> : <div className="detail-placeholder"><Mail size={36} /><p>Vyberte e-mail ze seznamu.</p></div>}</section>{templatesOpen && <EmailTemplatesModal onClose={() => setTemplatesOpen(false)} />}</div>;
}

function formatDate(value: string) { return new Date(value).toLocaleDateString("cs-CZ", { day: "2-digit", month: "2-digit" }); }
