import { useEffect, useState } from "react";
import { Send } from "lucide-react";
import { api } from "../../api";
import type { EmailMessage, EmailTemplate } from "../../domain";
import { RichTextEditor } from "./RichTextEditor";

export function EmailComposer({ email, onClose, onSent }: { email: EmailMessage; onClose: () => void; onSent: (email: EmailMessage) => void }) {
  const [templates, setTemplates] = useState<EmailTemplate[]>([]); const [toAddress, setToAddress] = useState(email.direction === "Inbound" ? email.fromAddress : email.toAddress); const [ccAddress, setCcAddress] = useState(""); const [subject, setSubject] = useState(email.subject.toLowerCase().startsWith("re:") ? email.subject : `Re: ${email.subject}`); const [bodyHtml, setBodyHtml] = useState("<p></p>"); const [sending, setSending] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { api.emailTemplates.list().then(setTemplates).catch(() => setError("Šablony se nepodařilo načíst.")); }, []);
  const insertTemplate = (id: string) => { const template = templates.find(x => x.id === id); if (!template) return; setBodyHtml(template.bodyHtml); if (template.subject) setSubject(template.subject); };
  const send = async (event: React.FormEvent) => { event.preventDefault(); setSending(true); setError(undefined); try { onSent(await api.emails.send({ toAddress: toAddress.trim(), ccAddress: ccAddress.trim() || undefined, subject: subject.trim(), bodyHtml, replyToEmailId: email.id, businessPartnerId: email.businessPartnerId, orderId: email.orderId })); } catch (caught) { setError(caught instanceof Error ? caught.message : "E-mail se nepodařilo odeslat."); } finally { setSending(false); } };
  return <div className="modal-backdrop"><section className="settings-modal composer-modal"><header><div><p className="eyebrow">ODPOVĚĎ</p><h2>Nový e-mail</h2></div><button className="secondary" onClick={onClose}>Zavřít</button></header><form onSubmit={send}>{error && <div className="error-banner">{error}</div>}<div className="composer-fields"><label><span>Komu</span><input required type="email" value={toAddress} onChange={e => setToAddress(e.target.value)} /></label><label><span>Kopie</span><input type="email" value={ccAddress} onChange={e => setCcAddress(e.target.value)} /></label><label className="wide"><span>Předmět</span><input required value={subject} onChange={e => setSubject(e.target.value)} /></label><label className="wide"><span>Vložit šablonu</span><select defaultValue="" onChange={e => { insertTemplate(e.target.value); e.currentTarget.value = ""; }}><option value="">Vyberte šablonu…</option>{templates.map(template => <option key={template.id} value={template.id}>{template.name}</option>)}</select><small>Obsah šablony se zkopíruje do editoru a lze jej libovolně změnit.</small></label></div><RichTextEditor value={bodyHtml} onChange={setBodyHtml} /><footer><button type="button" className="secondary" onClick={onClose}>Zrušit</button><button className="primary" disabled={sending}><Send size={15} /> {sending ? "Odesílám…" : "Odeslat"}</button></footer></form></section></div>;
}
