import { useMemo, useState } from "react";
import { FileText, LoaderCircle, Mail, Paperclip, RefreshCw, Search } from "lucide-react";
import { EmailDetail } from "./EmailDetail";
import { EmailTemplatesModal } from "./EmailTemplatesModal";
import { useEmailsWorkspace } from "./useEmailsWorkspace";
import { SortableHeader } from "../../shared/SortableHeader";

export function EmailsWorkspace({ onOpenSettings, onCreateOrder, onCreatePartner }: { onOpenSettings: () => void; onCreateOrder: (customerId: string | undefined, email: import("../../domain").EmailMessage) => void; onCreatePartner: (type: import("../../domain").PartnerType, email: import("../../domain").EmailMessage) => void }) {
  const state = useEmailsWorkspace(onOpenSettings); const [templatesOpen, setTemplatesOpen] = useState(false); const [sortBy, setSortBy] = useState<"address" | "subject" | "assignment" | "direction" | "attachment" | "date">("date"); const [descending, setDescending] = useState(true);
  const emails = useMemo(() => { const value = (email: import("../../domain").EmailMessage) => ({ address: email.direction === "Outbound" ? email.toAddress : email.fromName || email.fromAddress, subject: email.subject, assignment: email.businessPartnerName || email.orderNumber || "", direction: email.direction, attachment: email.hasAttachments ? "1" : "0", date: email.occurredAtUtc })[sortBy]; return [...state.emails].sort((left, right) => value(left).localeCompare(value(right), "cs", { sensitivity: "base" }) * (descending ? -1 : 1)); }, [state.emails, sortBy, descending]);
  const sort = (key: typeof sortBy) => { if (sortBy === key) setDescending(value => !value); else { setSortBy(key); setDescending(false); } };
  return <div className="split-view email-workspace"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">KOMUNIKACE</p><h1>E-maily</h1></div><div className="email-actions"><button className="secondary" onClick={() => setTemplatesOpen(true)}><FileText size={15} /> Šablony</button><button className="primary email-sync" onClick={state.sync} disabled={state.syncing}>{state.syncing ? <LoaderCircle className="spin" size={15} /> : <RefreshCw size={15} />} Synchronizovat</button></div></header><div className="toolbar"><label className="search"><Search size={16} /><input value={state.search} onChange={event => state.setSearch(event.target.value)} placeholder="Hledat odesílatele nebo předmět…" /></label></div>{state.error && <div className="error-banner">{state.error}</div>}<div className="data-table-wrap">{state.loading ? <div className="loader"><LoaderCircle className="spin" /> Načítám e-maily…</div> : <table className="data-table email-table"><thead><tr><SortableHeader label="Od / Komu" active={sortBy === "address"} descending={descending} onSort={() => sort("address")} /><SortableHeader label="Předmět" active={sortBy === "subject"} descending={descending} onSort={() => sort("subject")} /><SortableHeader label="Přiřazení" active={sortBy === "assignment"} descending={descending} onSort={() => sort("assignment")} /><SortableHeader label="Směr" active={sortBy === "direction"} descending={descending} onSort={() => sort("direction")} /><SortableHeader label="Příloha" active={sortBy === "attachment"} descending={descending} onSort={() => sort("attachment")} /><SortableHeader label="Datum" active={sortBy === "date"} descending={descending} onSort={() => sort("date")} /></tr></thead><tbody>{emails.map(email => <tr key={email.id} className={`${state.selectedId === email.id ? "selected" : ""} ${email.isRead ? "" : "unread"}`} onClick={() => state.setSelectedId(email.id)}><td><strong>{email.direction === "Outbound" ? email.toAddress : email.fromName || email.fromAddress}</strong></td><td title={email.subject}>{email.subject}</td><td>{email.businessPartnerName || email.orderNumber || "Bez přiřazení"}</td><td>{email.direction === "Outbound" ? "Odeslaný" : "Přijatý"}</td><td className="icon-cell">{email.hasAttachments ? <Paperclip size={14} aria-label="Obsahuje přílohu" /> : "—"}</td><td>{formatDate(email.occurredAtUtc)}</td></tr>)}</tbody></table>}{!state.loading && state.emails.length === 0 && <div className="no-results">Schránka je prázdná. Nastavte účet a spusťte synchronizaci.</div>}</div></section><section className="detail-pane">{state.detail ? <EmailDetail email={state.detail} onChange={state.updateEmail} onSent={state.addEmail} onCreateOrder={onCreateOrder} onCreatePartner={onCreatePartner} /> : <div className="detail-placeholder"><Mail size={36} /><p>Vyberte e-mail ze seznamu.</p></div>}</section>{templatesOpen && <EmailTemplatesModal onClose={() => setTemplatesOpen(false)} />}</div>;
}

function formatDate(value: string) { return new Date(value).toLocaleDateString("cs-CZ", { day: "2-digit", month: "2-digit" }); }
