import { useState } from "react";
import { api } from "../../api";
import type { EmailMessage, EmailTransportQuoteContext } from "../../domain";

export function TransportQuoteModal({ email, context, onClose, onCreated }: { email: EmailMessage; context: EmailTransportQuoteContext; onClose: () => void; onCreated: () => void | Promise<void> }) {
  const [orderId, setOrderId] = useState(context.suggestedOrderId ?? ""); const [price, setPrice] = useState(0); const [currency, setCurrency] = useState("EUR"); const [pickupOn, setPickupOn] = useState(""); const [deliveryOn, setDeliveryOn] = useState(""); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); setError(undefined); try { await api.emails.createTransportQuote(email.id, { orderId, price, currency, pickupOn: pickupOn || null, deliveryOn: deliveryOn || null, notes: notes || null }); await onCreated(); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Nabídku dopravy se nepodařilo přiřadit."); } finally { setSaving(false); } };
  const suggested = context.orders.find(order => order.id === context.suggestedOrderId);
  return <div className="modal-backdrop"><section className="user-modal transport-quote-modal"><header><div><p className="eyebrow">NABÍDKA DOPRAVY</p><h2>Přiřadit k zakázce</h2></div><button onClick={onClose}>×</button></header><form onSubmit={save}>{error && <div className="error-banner">{error}</div>}<p>Dopravce <b>{context.carrier.name}</b> byl rozpoznán podle adresy nebo firemní domény.</p><label><span>Zakázka</span><select required value={orderId} onChange={event => setOrderId(event.target.value)}><option value="">Vyberte zakázku</option>{suggested && <optgroup label="Nalezeno v předmětu"><option value={suggested.id}>{suggested.number} · {suggested.title}</option></optgroup>}<optgroup label="Ostatní zakázky">{context.orders.filter(order => order.id !== context.suggestedOrderId).map(order => <option key={order.id} value={order.id}>{order.number} · {order.title} · {order.customerName}</option>)}</optgroup></select></label><div className="transport-quote-grid"><label><span>Cena</span><input required type="number" min="0" step="0.01" value={price} onChange={event => setPrice(Number(event.target.value))} /></label><label><span>Měna</span><input required pattern="[A-Za-z]{3}" minLength={3} maxLength={3} value={currency} onChange={event => setCurrency(event.target.value.toUpperCase())} /></label><label><span>Vyzvednutí</span><input type="date" value={pickupOn} onChange={event => setPickupOn(event.target.value)} /></label><label><span>Doručení</span><input type="date" min={pickupOn || undefined} value={deliveryOn} onChange={event => setDeliveryOn(event.target.value)} /></label></div><label><span>Poznámka</span><textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Doplňující podmínky nabídky…" /></label><footer><button type="button" className="secondary" onClick={onClose}>Zrušit</button><button className="primary" disabled={saving || !orderId}>{saving ? "Přiřazuji…" : "Přiřadit nabídku"}</button></footer></form></section></div>;
}
