server {
    listen 80;
    server_name localhost;

    location /bcg-hub/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /bcg-hub/index.html;
    }

    location = / {
        return 301 /bcg-hub/;
    }

    location = /bcg-hub {
        return 301 /bcg-hub/;
    }
}
