apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bcg-hub-data-protection-keys
  namespace: bcg-hub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
