import { useEffect, useState } from "react";
import { api, ApiError } from "./api";

export function EmailSettingsModal({ onClose }: { onClose: () => void }) {
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="settings-modal email-settings-modal"><header><div><p className="eyebrow">UŽIVATELSKÉ NASTAVENÍ</p><h2>Nastavení e-mailu</h2></div><button className="secondary" onClick={onClose}>Zavřít</button></header><EmailSettingsPanel onSaved={onClose} showCancel onCancel={onClose} /></section></div>;
}

export function EmailSettingsPanel({ onSaved, showCancel = false, onCancel }: { onSaved?: () => void; showCancel?: boolean; onCancel?: () => void }) {
  const [imapServer, setImapServer] = useState(""); const [imapPort, setImapPort] = useState(993); const [imapUsername, setImapUsername] = useState(""); const [imapPassword, setImapPassword] = useState(""); const [hasImapPassword, setHasImapPassword] = useState(false);
  const [smtpServer, setSmtpServer] = useState(""); const [smtpPort, setSmtpPort] = useState(587); const [smtpUsername, setSmtpUsername] = useState(""); const [smtpPassword, setSmtpPassword] = useState(""); const [hasSmtpPassword, setHasSmtpPassword] = useState(false);
  const [senderAddress, setSenderAddress] = useState(""); const [senderName, setSenderName] = useState(""); const [active, setActive] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { api.settings.getEmail().then(x => { setImapServer(x.imapServer); setImapPort(x.imapPort); setImapUsername(x.imapUsername); setHasImapPassword(x.hasImapPassword); setSmtpServer(x.smtpServer); setSmtpPort(x.smtpPort); setSmtpUsername(x.smtpUsername); setHasSmtpPassword(x.hasSmtpPassword); setSenderAddress(x.senderAddress); setSenderName(x.senderName ?? ""); setActive(x.isActive); }).catch(e => { if (!(e instanceof ApiError && e.status === 404)) setError("Nastavení se nepodařilo načíst."); }).finally(() => setLoading(false)); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(undefined); try { await api.settings.saveEmail({ imapServer: imapServer.trim(), imapPort, imapUseSsl: true, imapUsername: imapUsername.trim(), imapPassword, smtpServer: smtpServer.trim(), smtpPort, smtpUseSsl: true, smtpUsername: smtpUsername.trim(), smtpPassword, senderAddress: senderAddress.trim(), senderName: senderName.trim() || undefined, isActive: active }); setImapPassword(""); setSmtpPassword(""); setHasImapPassword(true); setHasSmtpPassword(true); onSaved?.(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Nastavení se nepodařilo uložit."); } finally { setSaving(false); } };
  const passwordPlaceholder = (saved: boolean, label: string) => saved ? "Heslo je uloženo, vyplňte jen pro změnu" : label;
  return loading ? <div className="loader">Načítám nastavení…</div> : <form className="email-settings-form" onSubmit={submit}>{error && <div className="error-banner">{error}</div>}<h3>Příchozí pošta (IMAP)</h3><div className="settings-grid"><Field label="IMAP server" value={imapServer} onChange={setImapServer} placeholder="imap.example.com" /><NumberField label="Port" value={imapPort} onChange={setImapPort} /><Field wide label="Uživatelské jméno" value={imapUsername} onChange={setImapUsername} type="text" /><Field wide label="Heslo" value={imapPassword} onChange={setImapPassword} type="password" required={!hasImapPassword} placeholder={passwordPlaceholder(hasImapPassword, "Heslo ke schránce")} /></div><h3>Odesílání (SMTP)</h3><div className="settings-grid"><Field label="SMTP server" value={smtpServer} onChange={setSmtpServer} placeholder="smtp.example.com" /><NumberField label="Port" value={smtpPort} onChange={setSmtpPort} /><Field wide label="Uživatelské jméno" value={smtpUsername} onChange={setSmtpUsername} type="text" /><Field wide label="Heslo" value={smtpPassword} onChange={setSmtpPassword} type="password" required={!hasSmtpPassword} placeholder={passwordPlaceholder(hasSmtpPassword, "Heslo pro SMTP")} /><Field label="Adresa odesílatele" value={senderAddress} onChange={setSenderAddress} type="email" /><Field label="Jméno odesílatele" value={senderName} onChange={setSenderName} required={false} /></div><label className="check settings-active"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Synchronizace a odesílání jsou aktivní</label><p className="settings-security">Připojení IMAP i SMTP používá SSL/TLS. Hesla jsou uložena šifrovaně.</p><footer>{showCancel && <button type="button" className="secondary" onClick={onCancel}>Zrušit</button>}<button className="primary" disabled={saving}>{saving ? "Ukládám…" : "Uložit"}</button></footer></form>;
}

function Field({ label, value, onChange, wide, type = "text", required = true, placeholder }: { label: string; value: string; onChange: (value: string) => void; wide?: boolean; type?: string; required?: boolean; placeholder?: string }) { return <label className={wide ? "wide" : ""}><span>{label}</span><input required={required} type={type} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} /></label>; }
function NumberField({ label, value, onChange }: { label: string; value: number; onChange: (value: number) => void }) { return <label><span>{label}</span><input required type="number" min="1" max="65535" value={value} onChange={e => onChange(Number(e.target.value))} /></label>; }
