import { useEffect, useState } from "react";
import { ApiError, api } from "./api";

export function EmailSettingsModal({ onClose }: { onClose: () => void }) {
  const [server, setServer] = useState(""); const [port, setPort] = useState(993); const [ssl, setSsl] = useState(true); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [hasPassword, setHasPassword] = useState(false); const [active, setActive] = useState(true); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { api.settings.getEmail().then(x => { setServer(x.imapServer); setPort(x.imapPort); setSsl(x.imapUseSsl); setUsername(x.imapUsername); setHasPassword(x.hasPassword); setActive(x.isActive); }).catch(e => { if (!(e instanceof ApiError && e.status === 404)) setError("Nastavení se nepodařilo načíst."); }).finally(() => setLoading(false)); }, []);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setSaving(true); setError(undefined); try { await api.settings.saveEmail({ imapServer: server.trim(), imapPort: port, imapUseSsl: ssl, imapUsername: username.trim(), imapPassword: password, isActive: active }); onClose(); } catch (e) { setError(e instanceof Error ? e.message : "Nastavení se nepodařilo uložit."); } finally { setSaving(false); } };
  return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><section className="settings-modal"><header><div><p className="eyebrow">UŽIVATELSKÉ NASTAVENÍ</p><h2>Nastavení e-mailu</h2></div><button className="secondary" onClick={onClose}>Zavřít</button></header>{loading ? <div className="loader">Načítám nastavení…</div> : <form onSubmit={submit}>{error && <div className="error-banner">{error}</div>}<h3>Příchozí pošta (IMAP)</h3><div className="settings-grid"><label><span>IMAP server</span><input required value={server} onChange={e => setServer(e.target.value)} placeholder="imap.example.com" /></label><label><span>Port</span><input required type="number" min="1" max="65535" value={port} onChange={e => setPort(Number(e.target.value))} /></label><label className="wide"><span>Uživatelské jméno (e-mail)</span><input required type="email" value={username} onChange={e => setUsername(e.target.value)} /></label><label className="wide"><span>Heslo</span><input type="password" required={!hasPassword} value={password} onChange={e => setPassword(e.target.value)} placeholder={hasPassword ? "Heslo je uloženo, vyplňte jen pro změnu" : "Heslo ke schránce"} /></label><label className="check"><input type="checkbox" checked={ssl} onChange={e => setSsl(e.target.checked)} /> Použít SSL/TLS</label><label className="check"><input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} /> Synchronizace je aktivní</label></div><footer><button type="button" className="secondary" onClick={onClose}>Zrušit</button><button className="primary" disabled={saving}>{saving ? "Ukládám…" : "Uložit"}</button></footer></form>}</section></div>;
}
