import { useEffect, useState } from "react";
import { AlertTriangle, Trash2 } from "lucide-react";
import { api } from "../../api";
import type { ComplaintDetail, ComplaintListItem, ComplaintStatus, OrderListItem, PartnerListItem, SaveComplaint } from "../../domain";
import { EntityResourcesPanel } from "../../shared/EntityResourcesPanel";

const statuses: { value: ComplaintStatus; label: string }[] = [{ value: "New", label: "Nová" }, { value: "InProgress", label: "Řeší se" }, { value: "Resolved", label: "Vyřešená" }, { value: "Rejected", label: "Zamítnutá" }];
const statusLabel = (status: ComplaintStatus) => statuses.find(x => x.value === status)?.label ?? status;
const empty = (): SaveComplaint => ({ reportedOn: new Date().toISOString().slice(0, 10), status: "New", customerId: "", orderId: "", description: "", version: 0 });

export function ComplaintsWorkspace() {
  const [items, setItems] = useState<ComplaintListItem[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [detail, setDetail] = useState<ComplaintDetail>(); const [editing, setEditing] = useState<SaveComplaint>();
  const load = () => api.complaints.list().then(result => { setItems(result); setSelectedId(current => current && result.some(x => x.id === current) ? current : result[0]?.id); });
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!selectedId) { setDetail(undefined); return; } const controller = new AbortController(); api.complaints.detail(selectedId, controller.signal).then(setDetail); return () => controller.abort(); }, [selectedId]);
  const save = async (value: SaveComplaint) => { const saved = detail ? await api.complaints.update(detail.id, value) : await api.complaints.create(value); setEditing(undefined); await load(); setSelectedId(saved.id); setDetail(saved); };
  return <div className="split-view"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">PÉČE O ZÁKAZNÍKY</p><h1>Reklamace</h1></div><button className="primary" onClick={() => { setDetail(undefined); setEditing(empty()); }}>+ Přidat</button></header><div className="partner-list">{items.map(item => <button key={item.id} className={`partner-row ${item.id === selectedId ? "selected" : ""}`} onClick={() => { setSelectedId(item.id); setEditing(undefined); }}><span className="partner-icon"><AlertTriangle size={18} /></span><span><b>{item.orderNumber} · {item.customer.name}</b><small>{new Date(item.reportedOn).toLocaleDateString("cs-CZ")} · {statusLabel(item.status)}</small></span></button>)}</div></section>{editing ? <ComplaintForm value={editing} onSave={save} onCancel={() => setEditing(undefined)} /> : <ComplaintDetailView complaint={detail} onEdit={() => detail && setEditing({ reportedOn: detail.reportedOn, status: detail.status, customerId: detail.customer.id, orderId: detail.orderId, description: detail.description ?? "", version: detail.version })} onDelete={async () => { if (!detail || !confirm("Opravdu reklamaci smazat?")) return; await api.complaints.remove(detail.id, detail.version); setDetail(undefined); setSelectedId(undefined); load(); }} />}</div>;
}

function ComplaintForm({ value, onSave, onCancel }: { value: SaveComplaint; onSave: (value: SaveComplaint) => void; onCancel: () => void }) {
  const [form, setForm] = useState(value); const [customers, setCustomers] = useState<PartnerListItem[]>([]); const [orders, setOrders] = useState<OrderListItem[]>([]);
  useEffect(() => { api.partners.list("Customer", "").then(x => setCustomers(x.items)); api.orders.list("", "number", true).then(x => setOrders(x.items)); }, []);
  const availableOrders = orders;
  return <section className="detail-pane"><form className="entity-form" onSubmit={event => { event.preventDefault(); onSave(form); }}><h2>{form.version ? "Upravit reklamaci" : "Nová reklamace"}</h2><label>Datum oznámení<input type="date" required value={form.reportedOn} onChange={event => setForm({ ...form, reportedOn: event.target.value })} /></label><label>Stav<select value={form.status} onChange={event => setForm({ ...form, status: event.target.value as ComplaintStatus })}>{statuses.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label>Zákazník<select required value={form.customerId} onChange={event => setForm({ ...form, customerId: event.target.value, orderId: "" })}><option value="">Vyberte zákazníka</option>{customers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Zakázka<select required value={form.orderId} onChange={event => setForm({ ...form, orderId: event.target.value })}><option value="">Vyberte zakázku</option>{availableOrders.map(x => <option key={x.id} value={x.id}>{x.number} · {x.title}</option>)}</select></label><label>Popis situace<textarea value={form.description ?? ""} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Jiné zboží, nesprávný počet, poškození…" /></label><div><button className="primary">Uložit</button><button type="button" className="secondary" onClick={onCancel}>Zrušit</button></div></form></section>;
}

function ComplaintDetailView({ complaint, onEdit, onDelete }: { complaint?: ComplaintDetail; onEdit: () => void; onDelete: () => void }) {
  const [tab, setTab] = useState<"overview" | "files" | "comments">("overview");
  if (!complaint) return <section className="detail-pane"><div className="detail-placeholder"><AlertTriangle size={36} /><p>Vyberte reklamaci ze seznamu.</p></div></section>;
  return <section className="detail-pane"><header className="detail-header"><div><h2>Reklamace k zakázce {complaint.orderNumber}</h2><p>{complaint.customer.name}</p></div><div><button className="secondary" onClick={onEdit}>Upravit</button><button className="icon-button" onClick={onDelete}><Trash2 size={16} /></button></div></header><nav className="tabs">{(["overview", "files", "comments"] as const).map(x => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{({ overview: "Přehled", files: "Soubory", comments: "Komentáře" })[x]}</button>)}</nav><div className="detail-content">{tab === "overview" && <div className="info-card wide"><p><b>Datum oznámení:</b> {new Date(complaint.reportedOn).toLocaleDateString("cs-CZ")}</p><p><b>Stav:</b> {statusLabel(complaint.status)}</p><p><b>Zákazník:</b> {complaint.customer.name}</p><p><b>Zakázka:</b> {complaint.orderNumber}</p><p>{complaint.description || "Bez popisu."}</p></div>}{tab === "files" && <EntityResourcesPanel ownerType="Complaint" ownerId={complaint.id} mode="files" />}{tab === "comments" && <EntityResourcesPanel ownerType="Complaint" ownerId={complaint.id} mode="comments" />}</div></section>;
}
