import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Search, Trash2 } from "lucide-react";
import { api } from "../../api";
import type { ComplaintDetail, ComplaintListItem, ComplaintStatus, OrderListItem, PartnerListItem, SaveComplaint } from "../../domain";
import { EntityResourcesPanel } from "../../shared/EntityResourcesPanel";
import { SortableHeader } from "../../shared/SortableHeader";

const statuses: { value: ComplaintStatus; label: string }[] = [{ value: "New", label: "Nová" }, { value: "InProgress", label: "Řeší se" }, { value: "Resolved", label: "Vyřešená" }, { value: "Rejected", label: "Zamítnutá" }];
const statusLabel = (status: ComplaintStatus) => statuses.find(x => x.value === status)?.label ?? status;
const empty = (): SaveComplaint => ({ reportedOn: new Date().toISOString().slice(0, 10), status: "New", customerId: "", orderId: "", description: "", version: 0 });

export function ComplaintsWorkspace() {
  const [items, setItems] = useState<ComplaintListItem[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [detail, setDetail] = useState<ComplaintDetail>(); const [editing, setEditing] = useState<SaveComplaint>(); const [search, setSearch] = useState(""); const [sortBy, setSortBy] = useState<"order" | "customer" | "reported" | "status" | "description">("reported"); const [descending, setDescending] = useState(true);
  const load = () => api.complaints.list().then(result => { setItems(result); setSelectedId(current => current && result.some(x => x.id === current) ? current : result[0]?.id); });
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!selectedId) { setDetail(undefined); return; } const controller = new AbortController(); api.complaints.detail(selectedId, controller.signal).then(setDetail); return () => controller.abort(); }, [selectedId]);
  const save = async (value: SaveComplaint) => { const saved = detail ? await api.complaints.update(detail.id, value) : await api.complaints.create(value); setEditing(undefined); await load(); setSelectedId(saved.id); setDetail(saved); };
  const visibleItems = useMemo(() => { const query = search.trim().toLocaleLowerCase("cs"); const filtered = query ? items.filter(item => [item.orderNumber, item.customer.name, statusLabel(item.status), item.description].some(value => value?.toLocaleLowerCase("cs").includes(query))) : items; const value = (item: ComplaintListItem) => ({ order: item.orderNumber, customer: item.customer.name, reported: item.reportedOn, status: statusLabel(item.status), description: item.description ?? "" })[sortBy]; return [...filtered].sort((left, right) => value(left).localeCompare(value(right), "cs", { sensitivity: "base" }) * (descending ? -1 : 1)); }, [items, search, sortBy, descending]);
  const sort = (key: typeof sortBy) => { if (sortBy === key) setDescending(value => !value); else { setSortBy(key); setDescending(false); } };
  return <div className="split-view"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">PÉČE O ZÁKAZNÍKY</p><h1>Reklamace</h1></div><button className="primary" onClick={() => { setDetail(undefined); setEditing(empty()); }}>+ Přidat</button></header><div className="toolbar"><label className="search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Hledat zakázku, zákazníka, stav nebo popis…" /></label></div><div className="data-table-wrap"><table className="data-table complaint-table"><thead><tr><SortableHeader label="Zakázka" active={sortBy === "order"} descending={descending} onSort={() => sort("order")} /><SortableHeader label="Zákazník" active={sortBy === "customer"} descending={descending} onSort={() => sort("customer")} /><SortableHeader label="Oznámeno" active={sortBy === "reported"} descending={descending} onSort={() => sort("reported")} /><SortableHeader label="Stav" active={sortBy === "status"} descending={descending} onSort={() => sort("status")} /><SortableHeader label="Popis" active={sortBy === "description"} descending={descending} onSort={() => sort("description")} /></tr></thead><tbody>{visibleItems.map(item => <tr key={item.id} className={item.id === selectedId ? "selected" : ""} onClick={() => { setSelectedId(item.id); setEditing(undefined); }}><td><strong>{item.orderNumber}</strong></td><td>{item.customer.name}</td><td>{new Date(item.reportedOn).toLocaleDateString("cs-CZ")}</td><td><span className={`status-badge ${item.status.toLowerCase()}`}>{statusLabel(item.status)}</span></td><td title={item.description}>{item.description || "—"}</td></tr>)}</tbody></table>{visibleItems.length === 0 && <div className="no-results">Žádné odpovídající reklamace.</div>}</div></section>{editing ? <ComplaintForm value={editing} onSave={save} onCancel={() => setEditing(undefined)} /> : <ComplaintDetailView complaint={detail} onEdit={() => detail && setEditing({ reportedOn: detail.reportedOn, status: detail.status, customerId: detail.customer.id, orderId: detail.orderId, description: detail.description ?? "", version: detail.version })} onDelete={async () => { if (!detail || !confirm("Opravdu reklamaci smazat?")) return; await api.complaints.remove(detail.id, detail.version); setDetail(undefined); setSelectedId(undefined); load(); }} />}</div>;
}

function ComplaintForm({ value, onSave, onCancel }: { value: SaveComplaint; onSave: (value: SaveComplaint) => void; onCancel: () => void }) {
  const [form, setForm] = useState(value); const [customers, setCustomers] = useState<PartnerListItem[]>([]); const [orders, setOrders] = useState<OrderListItem[]>([]);
  useEffect(() => { api.partners.list("Customer", "").then(x => setCustomers(x.items)); api.orders.list("", "number", true).then(x => setOrders(x.items)); }, []);
  const availableOrders = orders;
  return <section className="detail-pane partner-form-pane"><form className="partner-form" onSubmit={event => { event.preventDefault(); onSave(form); }}><header><div><p className="eyebrow">{form.version ? "ÚPRAVA REKLAMACE" : "NOVÁ REKLAMACE"}</p><h2>{form.version ? "Upravit reklamaci" : "Přidat reklamaci"}</h2><p>Údaje o reklamované zakázce a průběhu řešení.</p></div><div className="form-header-actions"><button type="button" className="secondary" onClick={onCancel}>Zavřít</button><button className="primary" disabled={!form.customerId || !form.orderId}>Uložit</button></div></header><div className="partner-form-content"><section className="form-card"><h3>Základní údaje</h3><p>Zakázka, zákazník a aktuální stav</p><div className="form-grid"><label><span>Datum oznámení</span><input type="date" required value={form.reportedOn} onChange={event => setForm({ ...form, reportedOn: event.target.value })} /></label><label><span>Stav</span><select value={form.status} onChange={event => setForm({ ...form, status: event.target.value as ComplaintStatus })}>{statuses.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label><label><span>Zákazník</span><select required value={form.customerId} onChange={event => setForm({ ...form, customerId: event.target.value, orderId: "" })}><option value="">Vyberte zákazníka</option>{customers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Zakázka</span><select required value={form.orderId} onChange={event => setForm({ ...form, orderId: event.target.value })}><option value="">Vyberte zakázku</option>{availableOrders.map(x => <option key={x.id} value={x.id}>{x.number} · {x.title}</option>)}</select></label></div></section><section className="form-card"><h3>Popis situace</h3><p>Průběh a rozsah reklamace</p><div className="form-grid"><label className="wide"><span>Popis</span><textarea value={form.description ?? ""} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Jiné zboží, nesprávný počet, poškození…" /></label></div></section></div></form></section>;
}

function ComplaintDetailView({ complaint, onEdit, onDelete }: { complaint?: ComplaintDetail; onEdit: () => void; onDelete: () => void }) {
  const [tab, setTab] = useState<"overview" | "files">("overview");
  if (!complaint) return <section className="detail-pane"><div className="detail-placeholder"><AlertTriangle size={36} /><p>Vyberte reklamaci ze seznamu.</p></div></section>;
  return <section className="detail-pane"><header className="detail-header"><div><h2>Reklamace k zakázce {complaint.orderNumber}</h2><p>{complaint.customer.name}</p></div><div><button className="secondary" onClick={onEdit}>Upravit</button><button className="icon-button" onClick={onDelete}><Trash2 size={16} /></button></div></header><nav className="tabs">{(["overview", "files"] as const).map(x => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{({ overview: "Přehled", files: "Soubory" })[x]}</button>)}</nav><div className="detail-body"><div className="detail-content">{tab === "overview" && <div className="overview-grid"><div className="info-card"><h3>Reklamace</h3><div className="info-row"><span>Datum oznámení</span><b>{new Date(complaint.reportedOn).toLocaleDateString("cs-CZ")}</b></div><div className="info-row"><span>Stav</span><b>{statusLabel(complaint.status)}</b></div></div><div className="info-card"><h3>Zakázka</h3><div className="info-row"><span>Zákazník</span><b>{complaint.customer.name}</b></div><div className="info-row"><span>Číslo zakázky</span><b>{complaint.orderNumber}</b></div></div><div className="info-card wide"><h3>Popis situace</h3><p>{complaint.description || "Bez popisu."}</p></div></div>}{tab === "files" && <EntityResourcesPanel ownerType="Complaint" ownerId={complaint.id} mode="files" />}</div><aside className="detail-comments"><EntityResourcesPanel ownerType="Complaint" ownerId={complaint.id} mode="comments" /></aside></div></section>;
}
