import { FileUp, LoaderCircle, Search } from "lucide-react";
import type { OrderListItem, OrderSalesChannel } from "../../domain";
import { Pagination } from "../../shared/Pagination";
import { formatDate } from "./formatters";

interface Props { orders: OrderListItem[]; totalCount: number; page: number; pageSize: number; selectedId?: string; search: string; salesChannel: OrderSalesChannel; sortBy: string; descending: boolean; loading: boolean; error?: string; setSelectedId: (id: string) => void; setSearch: (value: string) => void; setSalesChannel: (value: OrderSalesChannel) => void; setSortBy: (value: string) => void; setDescending: (update: (current: boolean) => boolean) => void; setPage: (page: number) => void; onCreate: () => void; onImport: () => void }

const columns = [{ key: "number", label: "ID zakázky" }, { key: "title", label: "Název zakázky" }, { key: "customer", label: "Název zákazníka" }, { key: "received", label: "Datum přijetí" }, { key: "carrier", label: "Dopravce" }];

export function OrderListPane(props: Props) {
  const sort = (key: string) => { if (props.sortBy === key) props.setDescending(current => !current); else { props.setSortBy(key); if (props.descending) props.setDescending(() => false); } };
  return <section className="list-pane"><header className="pane-header"><div><p className="eyebrow">OBCHOD A LOGISTIKA</p><h1>Zakázky</h1></div><div className="pane-actions"><button className="secondary" onClick={props.onImport}><FileUp size={16} /> Import z Pohody</button><button className="primary" onClick={props.onCreate}>+ Nová zakázka</button></div></header><div className="order-channel-filter" role="group" aria-label="Typ zakázek">{[["Wholesale", "Zobrazit velkosklad"], ["Eshop", "Zobrazit eshop"], ["All", "Zobrazit všechny"]].map(([value, label]) => <button type="button" key={value} className={props.salesChannel === value ? "active" : ""} aria-pressed={props.salesChannel === value} onClick={() => props.setSalesChannel(value as OrderSalesChannel)}>{label}</button>)}</div><div className="toolbar"><label className="search"><Search size={16} /><input value={props.search} onChange={event => props.setSearch(event.target.value)} placeholder="Hledat podle ID, zakázky nebo zákazníka…" /></label></div>{props.error && <div className="error-banner">{props.error}</div>}<div className="order-table-wrap">{props.loading ? <div className="loader"><LoaderCircle className="spin" /> Načítám…</div> : <table className="order-table"><thead><tr>{columns.map(column => <th key={column.key}><button onClick={() => sort(column.key)}>{column.label}<span className={props.sortBy === column.key ? "active" : ""}>{props.sortBy === column.key ? props.descending ? "↓" : "↑" : "↕"}</span></button></th>)}</tr></thead><tbody>{props.orders.map(order => <tr key={order.id} className={props.selectedId === order.id ? "selected" : ""} onClick={() => props.setSelectedId(order.id)}><td>{order.number}</td><td>{order.title}</td><td>{order.customerName}</td><td>{formatDate(order.orderedOn)}</td><td>{order.carrierName || "—"}</td></tr>)}</tbody></table>}</div><Pagination page={props.page} pageSize={props.pageSize} totalCount={props.totalCount} onPageChange={props.setPage} /></section>;
}
