import { useEffect, useState } from "react";
import { Trash2, Truck } from "lucide-react";
import { api } from "../../api";
import type { OrderDetail, PartnerListItem } from "../../domain";
import { formatDate, formatMoney } from "./formatters";

export function OrderOverview({ order }: { order: OrderDetail }) { return <div className="overview-grid"><Info title="Termíny" rows={[["Objednáno", formatDate(order.orderedOn)], ["Požadované doručení", formatDate(order.requestedDeliveryOn)], ["Nakládka", formatDate(order.plannedPickupOn)], ["Doručení", formatDate(order.plannedDeliveryOn)]]} /><Info title="Objem zakázky" rows={[["Hodnota", formatMoney(order.valueCzk)], ["Hmotnost", `${order.weightKg.toLocaleString("cs-CZ")} kg`], ["Objem", `${order.volumeM3.toLocaleString("cs-CZ")} m³`]]} /><Info title="Partneři" rows={[["Sklad", order.warehouse?.name ?? "—"], ["Dopravce", order.carrier?.name ?? "—"], ["Celní deklarant", order.customsDeclarant?.name ?? "—"]]} /><div className="info-card wide"><h3>Pokyny skladu</h3><p>{order.warehouseInstructions ?? "Zatím nebyly zadány žádné pokyny."}</p></div><QuoteManager order={order} /></div>; }

function QuoteManager({ order }: { order: OrderDetail }) { const [carriers, setCarriers] = useState<PartnerListItem[]>([]); const [carrierId, setCarrierId] = useState(""); const [price, setPrice] = useState(0); const [quotes, setQuotes] = useState(order.transportQuotes); useEffect(() => { setQuotes(order.transportQuotes); api.partners.list("Carrier", "").then(x => setCarriers(x.items)); }, [order]); return <div className="info-card wide"><h3><Truck size={17} /> Nabídky dopravy</h3><div className="resource-row"><select value={carrierId} onChange={e => setCarrierId(e.target.value)}><option value="">Dopravce</option>{carriers.map(x => <option value={x.id} key={x.id}>{x.name}</option>)}</select><input type="number" min="0" value={price} onChange={e => setPrice(Number(e.target.value))} /><button className="primary" disabled={!carrierId} onClick={async () => { const quote = await api.orders.addQuote(order.id, { carrierId, price, currency: "EUR", isSelected: false, version: 0 }); setQuotes(x => [...x, quote]); }}>Přidat</button></div>{quotes.map(quote => <div className="quote resource-row" key={quote.id}><b>{quote.carrier.name}</b><span>{quote.price.toLocaleString("cs-CZ")} {quote.currency}</span><label><input type="checkbox" checked={quote.isSelected} onChange={async e => { const updated = await api.orders.updateQuote(order.id, quote.id, { carrierId: quote.carrier.id, price: quote.price, currency: quote.currency, pickupOn: quote.pickupOn, deliveryOn: quote.deliveryOn, isSelected: e.target.checked, notes: quote.notes, version: quote.version }); setQuotes(items => items.map(x => x.id === quote.id ? updated : { ...x, isSelected: false })); }} /> Vybraná</label><button className="icon-button" onClick={async () => { await api.orders.removeQuote(order.id, quote.id, quote.version); setQuotes(x => x.filter(y => y.id !== quote.id)); }}><Trash2 size={15} /></button></div>)}</div>; }
function Info({ title, rows }: { title: string; rows: string[][] }) { return <div className="info-card"><h3>{title}</h3>{rows.map(([label, value]) => <div className="info-row" key={label}><span>{label}</span><b>{value}</b></div>)}</div>; }
