import { useEffect, useState } from "react";
import { api } from "../../api";
import type { OrderDetail, PartnerListItem, SaveOrder } from "../../domain";

export function OrderEditor({ order, onClose, onSaved }: { order?: OrderDetail; onClose: () => void; onSaved: () => void }) {
  const numberPrefix = `BCG_${new Date().getFullYear()}`;
  const [customers, setCustomers] = useState<PartnerListItem[]>([]); const [warehouses, setWarehouses] = useState<PartnerListItem[]>([]); const [carriers, setCarriers] = useState<PartnerListItem[]>([]);
  const [form, setForm] = useState<SaveOrder>({ number: order?.number ?? numberPrefix, pohodaOrderNumber: order?.pohodaOrderNumber, title: order?.title ?? "", status: order?.status ?? "New", customerId: order?.customer.id ?? "", customerContactId: order?.customerContactId, warehouseId: order?.warehouse?.id, carrierId: order?.carrier?.id, customsDeclarantId: order?.customsDeclarant?.id, orderedOn: order?.orderedOn, requestedDeliveryOn: order?.requestedDeliveryOn, plannedPickupOn: order?.plannedPickupOn, plannedDeliveryOn: order?.plannedDeliveryOn, valueCzk: order?.valueCzk ?? 0, weightKg: order?.weightKg ?? 0, volumeM3: order?.volumeM3 ?? 0, warehouseInstructions: order?.warehouseInstructions, version: order?.version ?? 0 });
  useEffect(() => { api.partners.list("Customer", "").then(x => setCustomers(x.items)); api.partners.list("Warehouse", "").then(x => setWarehouses(x.items)); api.partners.list("Carrier", "").then(x => setCarriers(x.items)); }, []);
  const set = (key: keyof SaveOrder, value: unknown) => setForm(current => ({ ...current, [key]: value || undefined }));
  return <section className="detail-pane"><form className="entity-form" onSubmit={async event => { event.preventDefault(); if (order) await api.orders.update(order.id, form); else await api.orders.create(form); onSaved(); }}><h2>{order ? "Upravit zakázku" : "Nová zakázka"}</h2><label>Číslo<input required value={form.number} onChange={e => set("number", e.target.value)} /></label><label>Název<input required value={form.title} onChange={e => set("title", e.target.value)} /></label><label>Zákazník<select required value={form.customerId} onChange={e => set("customerId", e.target.value)}><option value="">Vyberte</option>{customers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Sklad<select value={form.warehouseId ?? ""} onChange={e => set("warehouseId", e.target.value)}><option value="">—</option>{warehouses.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Dopravce<select value={form.carrierId ?? ""} onChange={e => set("carrierId", e.target.value)}><option value="">—</option>{carriers.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Hodnota Kč<input type="number" min="0" value={form.valueCzk} onChange={e => set("valueCzk", Number(e.target.value))} /></label><label>Hmotnost kg<input type="number" min="0" value={form.weightKg} onChange={e => set("weightKg", Number(e.target.value))} /></label><label>Objem m³<input type="number" min="0" value={form.volumeM3} onChange={e => set("volumeM3", Number(e.target.value))} /></label><label>Objednáno<input type="date" value={form.orderedOn ?? ""} onChange={e => set("orderedOn", e.target.value)} /></label><label>Plán doručení<input type="date" value={form.plannedDeliveryOn ?? ""} onChange={e => set("plannedDeliveryOn", e.target.value)} /></label><label>Pokyny skladu<textarea value={form.warehouseInstructions ?? ""} onChange={e => set("warehouseInstructions", e.target.value)} /></label><div><button className="primary">Uložit</button><button type="button" className="secondary" onClick={onClose}>Zrušit</button></div></form></section>;
}
