import { useState } from "react";
import { Check, Pencil, Plus, Trash2, X } from "lucide-react";
import { api } from "../../api";
import type { ContactPerson, PartnerDetail } from "../../domain";
import { formatPhone } from "../../shared/phone";

export function PartnerContactsTable({ partner, onReload }: { partner: PartnerDetail; onReload: () => void }) {
  const [form, setForm] = useState<Partial<ContactPerson>>();
  const save = async () => { if (!form?.fullName?.trim()) return; const value = { fullName: form.fullName.trim(), position: form.position, email: form.email, phone: form.phone, isPrimary: !!form.isPrimary, version: form.version ?? 0 }; if (form.id) await api.partners.updateContact(partner.id, form.id, value); else await api.partners.addContact(partner.id, value); setForm(undefined); onReload(); };
  const editRow = (contact: ContactPerson) => form?.id === contact.id ? <ContactInputs form={form} setForm={setForm} /> : <><td><strong>{contact.fullName}</strong></td><td>{contact.email || "—"}</td><td>{formatPhone(contact.phone)}</td></>;
  return <section className="info-card wide contacts-table-card"><header><h3>Kontaktní osoby</h3><button className="secondary compact" onClick={() => setForm({})}><Plus size={14} /> Přidat kontakt</button></header><div className="data-table-wrap embedded"><table className="data-table contacts-table"><thead><tr><th>Jméno</th><th>E-mail</th><th>Telefon</th><th className="actions">Akce</th></tr></thead><tbody>{form && !form.id && <tr className="editing"><ContactInputs form={form} setForm={setForm} /><td className="actions"><ContactActions canSave={!!form.fullName?.trim()} onSave={save} onCancel={() => setForm(undefined)} /></td></tr>}{partner.contacts.map(contact => <tr key={contact.id} className={form?.id === contact.id ? "editing" : undefined}>{editRow(contact)}<td className="actions">{form?.id === contact.id ? <ContactActions canSave={!!form.fullName?.trim()} onSave={save} onCancel={() => setForm(undefined)} /> : <><button className="icon-button" title="Upravit kontakt" onClick={() => setForm(contact)}><Pencil size={14} /></button><button className="icon-button" title="Smazat kontakt" onClick={async () => { await api.partners.removeContact(partner.id, contact.id, contact.version); onReload(); }}><Trash2 size={14} /></button></>}</td></tr>)}</tbody></table>{partner.contacts.length === 0 && !form && <div className="contacts-empty">Zatím nebyly přidány žádné kontaktní osoby.</div>}</div></section>;
}

function ContactInputs({ form, setForm }: { form: Partial<ContactPerson>; setForm: (value: Partial<ContactPerson>) => void }) { return <><td><input aria-label="Jméno" placeholder="Jméno" autoFocus value={form.fullName ?? ""} onChange={e => setForm({ ...form, fullName: e.target.value })} /></td><td><input aria-label="E-mail" type="email" placeholder="E-mail" value={form.email ?? ""} onChange={e => setForm({ ...form, email: e.target.value })} /></td><td><input aria-label="Telefon" type="tel" placeholder="Telefon" value={form.phone ?? ""} onChange={e => setForm({ ...form, phone: e.target.value })} /></td></>; }

function ContactActions({ canSave, onSave, onCancel }: { canSave: boolean; onSave: () => void; onCancel: () => void }) { return <div className="contact-actions"><button className="icon-button save" title="Uložit kontakt" disabled={!canSave} onClick={onSave}><Check size={15} /></button><button className="icon-button" title="Zrušit úpravy" onClick={onCancel}><X size={15} /></button></div>; }
