import { useEffect, useMemo, useState } from "react";
import { ArrowUpDown, Building2, Search, Trash2 } from "lucide-react";
import { api } from "../../api";
import type { ContactPerson, PartnerDetail, PartnerListItem, PartnerType, SavePartner } from "../../domain";
import { CommunicationPanel } from "../../shared/CommunicationPanel";
import { EntityResourcesPanel } from "../../shared/EntityResourcesPanel";

const empty = (type: PartnerType): SavePartner => ({ type, name: "", version: 0 });

export function PartnerWorkspace({ type, title }: { type: PartnerType; title: string }) {
  const [items, setItems] = useState<PartnerListItem[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [detail, setDetail] = useState<PartnerDetail>(); const [search, setSearch] = useState(""); const [descending, setDescending] = useState(false); const [editing, setEditing] = useState<SavePartner>(); const [error, setError] = useState<string>();
  const load = () => api.partners.list(type, search).then(result => { setItems(result.items); setSelectedId(current => current && result.items.some(x => x.id === current) ? current : result.items[0]?.id); });
  useEffect(() => { const timer = window.setTimeout(() => load().catch(() => setError("Seznam se nepodařilo načíst.")), 180); return () => window.clearTimeout(timer); }, [type, search]);
  useEffect(() => { if (!selectedId) { setDetail(undefined); return; } const controller = new AbortController(); api.partners.detail(selectedId, controller.signal).then(setDetail); return () => controller.abort(); }, [selectedId]);
  const sorted = useMemo(() => [...items].sort((a, b) => a.name.localeCompare(b.name, "cs") * (descending ? -1 : 1)), [items, descending]);
  const save = async (value: SavePartner) => { const saved = detail ? await api.partners.update(detail.id, value) : await api.partners.create(value); setEditing(undefined); await load(); setSelectedId(saved.id); setDetail(saved); };
  return <div className="split-view"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">CRM A KONTAKTY</p><h1>{title}</h1></div><button className="primary" onClick={() => { setDetail(undefined); setEditing(empty(type)); }}>+ Přidat</button></header><div className="toolbar"><label className="search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Hledat…" /></label><button className="icon-button" onClick={() => setDescending(x => !x)}><ArrowUpDown size={17} /></button></div>{error && <div className="error-banner">{error}</div>}<div className="partner-list">{sorted.map(item => <button key={item.id} className={`partner-row ${item.id === selectedId ? "selected" : ""}`} onClick={() => { setSelectedId(item.id); setEditing(undefined); }}><span className="partner-icon"><Building2 size={18} /></span><span><b>{item.name}</b><small>{[item.city, item.countryCode].filter(Boolean).join(", ") || "Adresa není vyplněna"}</small></span><em>{item.contactCount}</em></button>)}</div></section>{editing ? <PartnerForm value={editing} onCancel={() => setEditing(undefined)} onSave={save} /> : <PartnerDetailView partner={detail} onEdit={() => detail && setEditing({ ...detail })} onDelete={async () => { if (!detail || !confirm("Opravdu záznam smazat?")) return; await api.partners.remove(detail.id, detail.version); setDetail(undefined); setSelectedId(undefined); load(); }} onReload={() => detail && api.partners.detail(detail.id).then(setDetail)} />}</div>;
}

function PartnerForm({ value, onSave, onCancel }: { value: SavePartner; onSave: (value: SavePartner) => void; onCancel: () => void }) {
  const [form, setForm] = useState(value); const field = (key: keyof SavePartner, label: string, options?: { wide?: boolean; type?: string; placeholder?: string; maxLength?: number }) => <label className={options?.wide ? "wide" : undefined}><span>{label}</span><input type={options?.type} maxLength={options?.maxLength} placeholder={options?.placeholder} value={String(form[key] ?? "")} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>;
  return <section className="detail-pane partner-form-pane"><form className="partner-form" onSubmit={event => { event.preventDefault(); onSave(form); }}><header><div><p className="eyebrow">{form.version ? "ÚPRAVA ZÁZNAMU" : "NOVÝ ZÁZNAM"}</p><h2>{form.version ? "Upravit údaje" : "Přidat nový záznam"}</h2><p>Vyplňte základní údaje. Ostatní informace můžete doplnit později.</p></div><div className="form-header-actions"><button type="button" className="secondary" onClick={onCancel}>Zavřít</button><button className="primary" disabled={!form.name.trim()}>Uložit</button></div></header><div className="partner-form-content"><section className="form-card"><h3>Firemní a kontaktní údaje</h3><p>Identifikace a hlavní kontaktní kanály</p><div className="form-grid">{field("name", "Název", { wide: true, placeholder: "Např. BCG Logistics s.r.o." })}{field("companyNumber", "IČ", { placeholder: "12345678" })}{field("vatNumber", "DIČ", { placeholder: "CZ12345678" })}{field("email", "E-mail", { type: "email", placeholder: "info@firma.cz" })}{field("phone", "Telefon", { type: "tel", placeholder: "+420 123 456 789" })}{field("website", "Web", { wide: true, type: "url", placeholder: "https://www.firma.cz" })}</div></section><section className="form-card"><h3>Adresa</h3><p>Sídlo nebo provozovna</p><div className="form-grid address-grid">{field("street", "Ulice a číslo", { wide: true, placeholder: "Průmyslová 123" })}{field("city", "Město", { placeholder: "Praha" })}{field("postalCode", "PSČ", { placeholder: "110 00" })}{field("countryCode", "Země", { placeholder: "CZ", maxLength: 2 })}</div></section><section className="form-card"> <h3>Doplňující informace</h3><div className="form-grid"><label className="wide"><span>Poznámky</span><textarea placeholder="Interní poznámky k záznamu…" value={form.notes ?? ""} onChange={event => setForm({ ...form, notes: event.target.value })} /></label>{form.type === "Carrier" && <label className="wide"><span>Možnosti přepravy</span><textarea value={form.transportCapabilities ?? ""} onChange={event => setForm({ ...form, transportCapabilities: event.target.value })} /></label>}</div></section></div></form></section>;
}

function PartnerDetailView({ partner, onEdit, onDelete, onReload }: { partner?: PartnerDetail; onEdit: () => void; onDelete: () => void; onReload: () => void }) {
  const [tab, setTab] = useState<"overview" | "contacts" | "communication" | "files" | "comments">("overview");
  if (!partner) return <section className="detail-pane"><div className="detail-placeholder"><Building2 size={36} /><p>Vyberte záznam ze seznamu.</p></div></section>;
  return <section className="detail-pane"><header className="detail-header"><div><h2>{partner.name}</h2><p>{[partner.street, partner.city, partner.countryCode].filter(Boolean).join(", ")}</p></div><div><button className="secondary" onClick={onEdit}>Upravit</button><button className="icon-button" onClick={onDelete}><Trash2 size={16} /></button></div></header><nav className="tabs">{(["overview", "contacts", "communication", "files", "comments"] as const).map(x => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{({ overview: "Přehled", contacts: "Kontakty", communication: "Komunikace", files: "Soubory", comments: "Komentáře" })[x]}</button>)}</nav><div className="detail-content">{tab === "overview" && <div className="overview-grid"><div className="info-card"><h3>Firemní údaje</h3><div className="info-row"><span>IČ</span><b>{partner.companyNumber || "—"}</b></div><div className="info-row"><span>DIČ</span><b>{partner.vatNumber || "—"}</b></div></div><div className="info-card"><h3>Kontaktní údaje</h3><div className="info-row"><span>E-mail</span><b>{partner.email || "—"}</b></div><div className="info-row"><span>Telefon</span><b>{partner.phone || "—"}</b></div></div><div className="info-card wide"><h3>Poznámky</h3><p>{partner.notes || "Zatím nebyly zadány žádné poznámky."}</p></div></div>}{tab === "contacts" && <Contacts partner={partner} onReload={onReload} />}{tab === "communication" && <CommunicationPanel partnerId={partner.id} />}{tab === "files" && <EntityResourcesPanel ownerType="BusinessPartner" ownerId={partner.id} mode="files" />}{tab === "comments" && <EntityResourcesPanel ownerType="BusinessPartner" ownerId={partner.id} mode="comments" />}</div></section>;
}

function Contacts({ partner, onReload }: { partner: PartnerDetail; onReload: () => void }) {
  const [form, setForm] = useState<Partial<ContactPerson>>({}); const save = async () => { const value = { fullName: form.fullName, position: form.position, email: form.email, phone: form.phone, isPrimary: !!form.isPrimary, version: form.version ?? 0 }; if (form.id) await api.partners.updateContact(partner.id, form.id, value); else await api.partners.addContact(partner.id, value); setForm({}); onReload(); };
  return <div className="resource-panel"><section className="form-card"><h3>{form.id ? "Upravit kontakt" : "Nový kontakt"}</h3><p>Kontaktní osoba a její spojení</p><div className="form-grid"><label><span>Jméno</span><input placeholder="Jméno" value={form.fullName ?? ""} onChange={e => setForm({ ...form, fullName: e.target.value })} /></label><label><span>Pozice</span><input placeholder="Pozice" value={form.position ?? ""} onChange={e => setForm({ ...form, position: e.target.value })} /></label><label><span>E-mail</span><input type="email" placeholder="E-mail" value={form.email ?? ""} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label><span>Telefon</span><input type="tel" placeholder="Telefon" value={form.phone ?? ""} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label className="wide checkbox-field"><input type="checkbox" checked={!!form.isPrimary} onChange={e => setForm({ ...form, isPrimary: e.target.checked })} /><span>Hlavní kontakt</span></label><div className="wide form-actions"><button className="primary" disabled={!form.fullName} onClick={save}>Uložit kontakt</button></div></div></section>{partner.contacts.map(contact => <article className="info-card wide resource-row" key={contact.id} onClick={() => setForm(contact)}><span><b>{contact.fullName}{contact.isPrimary ? " · hlavní" : ""}</b><small>{[contact.position, contact.email, contact.phone].filter(Boolean).join(" · ")}</small></span><button className="icon-button" onClick={async event => { event.stopPropagation(); await api.partners.removeContact(partner.id, contact.id, contact.version); onReload(); }}><Trash2 size={15} /></button></article>)}</div>;
}
