import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowUpDown, Building2, Search, Trash2 } from "lucide-react";
import { api } from "../../api";
import type { OrderListItem, PartnerDetail, PartnerListItem, PartnerType, SavePartner } from "../../domain";
import { CommunicationPanel } from "../../shared/CommunicationPanel";
import { orderHref } from "../../shared/EntityLink";
import { EntityResourcesPanel } from "../../shared/EntityResourcesPanel";
import { formatPhone } from "../../shared/phone";
import { SortableHeader } from "../../shared/SortableHeader";
import { orderStatusLabels } from "../orders/formatters";
import { PartnerContactsTable } from "./PartnerContactsTable";

const empty = (type: PartnerType): SavePartner => ({ type, name: "", version: 0 });
const transportCapabilities = [{ value: "Road", label: "Silniční doprava", terms: ["road", "pozem", "silni"] }, { value: "Sea", label: "Námořní doprava", terms: ["sea", "námoř", "namor"] }, { value: "Air", label: "Letecká doprava", terms: ["air", "letec"] }];

export function PartnerWorkspace({ type, title, initialDraft, onInitialDraftHandled, onInitialDraftSaved, onInitialDraftCancelled }: { type: PartnerType; title: string; initialDraft?: SavePartner; onInitialDraftHandled?: () => void; onInitialDraftSaved?: (partner: PartnerDetail) => Promise<void>; onInitialDraftCancelled?: () => void }) {
  const requestedEntityId = new URLSearchParams(window.location.search).get("entityId") ?? undefined;
  const [items, setItems] = useState<PartnerListItem[]>([]); const [selectedId, setSelectedId] = useState<string | undefined>(requestedEntityId); const [detail, setDetail] = useState<PartnerDetail>(); const [search, setSearch] = useState(""); const [sortBy, setSortBy] = useState<keyof PartnerListItem>("name"); const [descending, setDescending] = useState(false); const [editing, setEditing] = useState<SavePartner | undefined>(initialDraft); const [error, setError] = useState<string>();
  const initialDraftPending = useRef(!!initialDraft);
  useEffect(() => { if (initialDraft) onInitialDraftHandled?.(); }, []);
  const load = () => api.partners.list(type, search).then(result => { setItems(result.items); setSelectedId(current => requestedEntityId && current === requestedEntityId ? current : current && result.items.some(x => x.id === current) ? current : result.items[0]?.id); });
  useEffect(() => { const timer = window.setTimeout(() => load().catch(() => setError("Seznam se nepodařilo načíst.")), 180); return () => window.clearTimeout(timer); }, [type, search]);
  useEffect(() => { if (!selectedId) { setDetail(undefined); return; } const controller = new AbortController(); api.partners.detail(selectedId, controller.signal).then(setDetail); return () => controller.abort(); }, [selectedId]);
  const sorted = useMemo(() => [...items].sort((a, b) => compare(a[sortBy], b[sortBy]) * (descending ? -1 : 1)), [items, sortBy, descending]);
  const sort = (key: keyof PartnerListItem) => { if (sortBy === key) setDescending(value => !value); else { setSortBy(key); setDescending(false); } };
  const save = async (value: SavePartner) => { const saved = value.version > 0 && detail ? await api.partners.update(detail.id, value) : await api.partners.create(value); if (initialDraftPending.current && onInitialDraftSaved) { initialDraftPending.current = false; try { await onInitialDraftSaved(saved); } catch { setError("Partner byl založen, ale e-mail se k němu nepodařilo automaticky přiřadit. Přiřaďte jej ručně v E-mailech."); } } setEditing(undefined); await load(); setSelectedId(saved.id); setDetail(saved); };
  const cancelEditing = () => { if (initialDraftPending.current) { initialDraftPending.current = false; onInitialDraftCancelled?.(); } setEditing(undefined); };
  return <div className="split-view"><section className="list-pane"><header className="pane-header"><div><p className="eyebrow">CRM A KONTAKTY</p><h1>{title}</h1></div><button className="primary" onClick={() => { initialDraftPending.current = false; setDetail(undefined); setEditing(empty(type)); }}>+ Přidat</button></header><div className="toolbar"><label className="search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Hledat podle názvu, města nebo kontaktu…" /></label><button className="icon-button" onClick={() => setDescending(x => !x)} title="Obrátit řazení"><ArrowUpDown size={17} /></button></div>{error && <div className="error-banner">{error}</div>}<div className="data-table-wrap"><table className="data-table partner-table"><thead><tr><SortableHeader label="Název" active={sortBy === "name"} descending={descending} onSort={() => sort("name")} /><SortableHeader label="Město" active={sortBy === "city"} descending={descending} onSort={() => sort("city")} /><SortableHeader label="Země" active={sortBy === "countryCode"} descending={descending} onSort={() => sort("countryCode")} /><SortableHeader label="E-mail" active={sortBy === "email"} descending={descending} onSort={() => sort("email")} /><SortableHeader label="Telefon" active={sortBy === "phone"} descending={descending} onSort={() => sort("phone")} /></tr></thead><tbody>{sorted.map(item => <tr key={item.id} className={item.id === selectedId ? "selected" : ""} onClick={() => { setSelectedId(item.id); setEditing(undefined); }}><td><strong>{item.name}</strong></td><td>{item.city || "—"}</td><td>{item.countryCode || "—"}</td><td title={item.email}>{item.email || "—"}</td><td>{formatPhone(item.phone)}</td></tr>)}</tbody></table></div></section>{editing ? <PartnerForm value={editing} onCancel={cancelEditing} onSave={save} /> : <PartnerDetailView partner={detail} onEdit={() => detail && setEditing({ ...detail })} onDelete={async () => { if (!detail || !confirm("Opravdu záznam smazat?")) return; await api.partners.remove(detail.id, detail.version); setDetail(undefined); setSelectedId(undefined); load(); }} onReload={() => detail && api.partners.detail(detail.id).then(setDetail)} />}</div>;
}

function compare(left: unknown, right: unknown) { if (typeof left === "number" && typeof right === "number") return left - right; return String(left ?? "").localeCompare(String(right ?? ""), "cs", { sensitivity: "base" }); }

function PartnerForm({ value, onSave, onCancel }: { value: SavePartner; onSave: (value: SavePartner) => void; onCancel: () => void }) {
  const [form, setForm] = useState(value); const field = (key: keyof SavePartner, label: string, options?: { wide?: boolean; type?: string; placeholder?: string; maxLength?: number }) => <label className={options?.wide ? "wide" : undefined}><span>{label}</span><input type={options?.type} maxLength={options?.maxLength} placeholder={options?.placeholder} value={String(form[key] ?? "")} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>;
  const hasCapability = (terms: string[]) => terms.some(term => (form.transportCapabilities ?? "").toLocaleLowerCase("cs").includes(term));
  const toggleCapability = (value: string, checked: boolean) => { const selected = transportCapabilities.filter(option => option.value === value ? checked : hasCapability(option.terms)).map(option => option.value); setForm({ ...form, transportCapabilities: selected.join(", ") }); };
  return <section className="detail-pane partner-form-pane"><form className={`partner-form${form.type === "Carrier" ? " carrier-form" : ""}`} onSubmit={event => { event.preventDefault(); onSave(form); }}><header><div><p className="eyebrow">{form.version ? "ÚPRAVA ZÁZNAMU" : "NOVÝ ZÁZNAM"}</p><h2>{form.version ? "Upravit údaje" : "Přidat nový záznam"}</h2><p>Vyplňte základní údaje. Ostatní informace můžete doplnit později.</p></div><div className="form-header-actions"><button type="button" className="secondary" onClick={onCancel}>Zavřít</button><button className="primary" disabled={!form.name.trim()}>Uložit</button></div></header><div className="partner-form-content"><section className="form-card"><h3>Firemní a kontaktní údaje</h3><p>Identifikace a hlavní kontaktní kanály</p><div className="form-grid">{field("name", "Název", { wide: true, placeholder: "Např. BCG Logistics s.r.o." })}{field("companyNumber", "IČ", { placeholder: "12345678" })}{field("vatNumber", "DIČ", { placeholder: "CZ12345678" })}{field("email", "E-mail", { type: "email", placeholder: "info@firma.cz" })}{field("phone", "Telefon", { type: "tel", placeholder: "+420 123 456 789" })}{field("website", "Web", { wide: true, type: "url", placeholder: "https://www.firma.cz" })}</div></section><section className="form-card"><h3>Adresa</h3><p>Sídlo nebo provozovna</p><div className="form-grid address-grid">{field("street", "Ulice a číslo", { wide: true, placeholder: "Průmyslová 123" })}{field("city", "Město", { placeholder: "Praha" })}{field("postalCode", "PSČ", { placeholder: "110 00" })}{field("countryCode", "Země", { placeholder: "CZ", maxLength: 2 })}</div></section><section className="form-card"><h3>Doplňující informace</h3>{form.type === "Carrier" && <fieldset className="transport-capabilities"><legend>Poskytované typy dopravy</legend>{transportCapabilities.map(option => <label key={option.value}><input type="checkbox" checked={hasCapability(option.terms)} onChange={event => toggleCapability(option.value, event.target.checked)} /><span>{option.label}</span></label>)}</fieldset>}<div className="form-grid"><label className="wide"><span>Poznámky</span><textarea placeholder="Interní poznámky k záznamu…" value={form.notes ?? ""} onChange={event => setForm({ ...form, notes: event.target.value })} /></label></div></section></div></form></section>;
}

function PartnerDetailView({ partner, onEdit, onDelete, onReload }: { partner?: PartnerDetail; onEdit: () => void; onDelete: () => void; onReload: () => void }) {
  const [tab, setTab] = useState<"overview" | "orders" | "communication" | "files">("overview");
  if (!partner) return <section className="detail-pane"><div className="detail-placeholder"><Building2 size={36} /><p>Vyberte záznam ze seznamu.</p></div></section>;
  const address = [partner.street, [partner.postalCode, partner.city].filter(Boolean).join(" "), partner.countryCode].filter(Boolean).join(", ");
  const websiteUrl = partner.website && (/^https?:\/\//i.test(partner.website) ? partner.website : `https://${partner.website}`);
  const tabs = partner.type === "Customer" ? ["overview", "orders", "communication", "files"] as const : ["overview", "communication", "files"] as const;
  return <section className="detail-pane"><header className="detail-header"><div><h2>{partner.name}</h2><p>{[partner.street, partner.city, partner.countryCode].filter(Boolean).join(", ")}</p></div><div><button className="secondary" onClick={onEdit}>Upravit</button><button className="icon-button" onClick={onDelete}><Trash2 size={16} /></button></div></header><nav className="tabs">{tabs.map(x => <button key={x} className={tab === x ? "active" : ""} onClick={() => setTab(x)}>{({ overview: "Přehled", orders: "Zakázky", communication: "Komunikace", files: "Soubory" })[x]}</button>)}</nav><div className="detail-body"><div className="detail-content">{tab === "overview" && <div className="overview-grid"><div className="info-card wide"><h3>Firemní údaje</h3><div className="info-row"><span>Název společnosti</span><b>{partner.name}</b></div><div className="info-row"><span>Adresa</span><b>{address || "—"}</b></div><div className="info-row"><span>Web</span><b>{websiteUrl ? <a className="external-link" href={websiteUrl} target="_blank" rel="noreferrer">{partner.website}</a> : "—"}</b></div><div className="info-row"><span>IČ</span><b>{partner.companyNumber || "—"}</b></div><div className="info-row"><span>DIČ</span><b>{partner.vatNumber || "—"}</b></div></div><PartnerContactsTable partner={partner} onReload={onReload} /><div className="info-card wide"><h3>Poznámky</h3><p>{partner.notes || "Zatím nebyly zadány žádné poznámky."}</p></div></div>}{tab === "orders" && <CustomerOrders partnerId={partner.id} />}{tab === "communication" && <CommunicationPanel partnerId={partner.id} />}{tab === "files" && <EntityResourcesPanel ownerType="BusinessPartner" ownerId={partner.id} mode="files" />}</div><aside className="detail-comments"><EntityResourcesPanel ownerType="BusinessPartner" ownerId={partner.id} mode="comments" /></aside></div></section>;
}

function CustomerOrders({ partnerId }: { partnerId: string }) {
  const [orders, setOrders] = useState<OrderListItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(undefined); loadCustomerOrders(partnerId, controller.signal).then(setOrders).catch(error => { if (error.name !== "AbortError") setError("Zakázky se nepodařilo načíst."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [partnerId]);
  if (loading) return <div className="loader">Načítám zakázky…</div>;
  if (error) return <div className="error-banner">{error}</div>;
  if (!orders.length) return <div className="detail-placeholder"><p>Zákazník zatím nemá žádné zakázky.</p></div>;
  return <div className="data-table-wrap customer-orders"><table className="data-table"><thead><tr><th>ID zakázky</th><th>Název zakázky</th><th>Datum přijetí</th><th>Stav</th></tr></thead><tbody>{orders.map(order => { const href = orderHref(order.id); return <tr key={order.id}><td><a href={href}><strong>{order.number}</strong></a></td><td><a href={href}>{order.title}</a></td><td><a href={href}>{order.orderedOn ? new Intl.DateTimeFormat("cs-CZ").format(new Date(`${order.orderedOn}T00:00:00`)) : "—"}</a></td><td><a href={href}>{orderStatusLabels[order.status]}</a></td></tr>; })}</tbody></table></div>;
}

async function loadCustomerOrders(partnerId: string, signal: AbortSignal) {
  const pageSize = 100; const orders: OrderListItem[] = []; let page = 1; let totalCount = 0;
  do { const result = await api.orders.list("", "number", true, signal, page, pageSize, partnerId); orders.push(...result.items); totalCount = result.totalCount; page++; } while (orders.length < totalCount);
  return orders;
}
